---
name: Test-NoXS
version: 1.01
author:
  - 'David A. Golden <dagolden@cpan.org>'
abstract: Prevent a module from loading its XS code
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Fcntl: 0
  Scalar::Util: 1.01
  Test::More: 0.45
provides:
  Test::NoXS:
    file: lib/Test/NoXS.pm
    version: 1.01
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
